# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 069329adbc3076f39e80761e3999a016a67a55e60ae10491462b14f90b224ba4b1742c3d18037e97facd8743dbb98be4fd0394ac5523722dd57f9f9060231167

test:
  secret_key_base: af86d15c02230c2e6d842821d3e134fa2e740ed35dee63883ca5bfa2c2612acc326946411bb3ccce226475e1e77a6761e3c020d25371b80d296c324699083310

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
